# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: windows-2022

variables:
- group: keystore-signing-variable-group

steps:
- task: UseDotNet@2
  displayName: 'Install .NET sdk'
  inputs:
    packageType: sdk
    version: 6.0.x
    installationPath: $(Agent.ToolsDirectory)/dotnet

- task: CmdLine@2
  displayName: 'Install Maui Workload'
  inputs:
    script: 'dotnet workload install maui'

- task: DownloadSecureFile@1
  name: keyStore
  displayName: 'Download keystore file'
  inputs:
    secureFile: 'pintpicks.keystore'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: './src/PintPicks/PintPicks.csproj'
    arguments: ' -c Release -f:net6.0-android /p:AndroidKeyStore=True /p:AndroidKeyStore=$(Agent.TempDirectory)\pintpicks.keystore /p:AndroidSigningStorePass=$(variables.keystore-password) /p:AndroidSigningKeyAlias=$(variables.key-alias) /p:AndroidSigningKeyPass=$(variables.key-password)'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Agent.builddirectory)'
    Contents: '**/*-Signed.aab'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    flattenFolders: true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'